<?php

namespace AppBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEpisodesForCalendar()
    {
        $query = $this->createQueryBuilder('episode')
            ->leftJoin('episode.season', 'season')
            ->addSelect('season')
            ->leftJoin('season.show', 'show')
            ->addSelect('show')
            ->where('episode.date >= CURRENT_DATE()')
            ->orderBy('episode.date', 'ASC')
            ->getQuery()
        ;

        return $query->getResult();
    }
}
